export const allAlumini = [
  {
    id: "1",
    name: "Ly Rithy",
    nameKh: "លី រិទ្ធី",
    faceBookLink: "https://www.facebook.com/mauu.kito",
    contact: "https://t.me/riththunhsahav",
    image: "/images/alumini/ly_rithy.jpeg",
  },
  {
    id: "2",
    name: "Rey Chenda",
    nameKh: "រ៉ី ចិន្តា",
    faceBookLink: "https://www.facebook.com/rey.channda",
    contact: "https://t.me/riththunhsahav",
    image: "/images/alumini/rey_channda.jpg",
  },
  {
    id: "3",
    name: "Eom Nakhem",
    nameKh: "អែម ណាឃីម",
    faceBookLink: "https://www.facebook.com/eom.nakhem",
    contact: "https://t.me/nakhimu",
    image: "/images/alumini/eom_nakhem.jpg",
  },
  {
    id: "4",
    name: "Khen Chen",
    nameKh: "ខេន ចិន",
    faceBookLink: "https://www.facebook.com/khen.chen.234382/",
    contact: "https://t.me",
    image: "/images/alumini/khen_chen.jpg",
  },
  {
    id: "5",
    name: "Sean Pheaktra",
    nameKh: "ស៊ាន ភត្រា",
    faceBookLink: "https://www.facebook.com/pheaktra.sean",
    contact: "https://t.me",
    image: "/images/alumini/sean_pheaktra.jpg",
  },
  {
    id: "6",
    name: "Phorn Sophea",
    nameKh: "ភន សុភា",
    faceBookLink: "https://www.facebook.com/nkaxt3uj0u",
    contact: "https://t.me",
    image: "/images/alumini/phorn_sophea.jpg",
  },
  {
    id: "7",
    name: "Mao Chomroeun",
    nameKh: "ម៉ៅ ចំរើន",
    faceBookLink: "https://www.facebook.com/mao.chomraoen",
    contact: "https://t.me",
    image: "/images/alumini/mao_chomroeun.jpg",
  },
  {
    id: "8",
    name: "Ra Sarin",
    nameKh: "រ៉ា សារិន",
    faceBookLink: "https://www.facebook.com/sarin.ry.1",
    contact: "https://t.me/Jackphydepole",
    image: "/images/cards/sarin.jpg",
  },
  {
    id: "9",
    name: "Lam Long",
    nameKh: "ឡាំ ឡុង",
    faceBookLink: "https://www.facebook.com/lamlong.geography",
    contact: "https://t.me",
    image: "/images/alumini/lam_long.jpg",
  },
  {
    id: "10",
    name: "Hong Pisey",
    nameKh: "ហុង ពិសី",
    faceBookLink: "https://www.facebook.com/ab3sodwdh2",
    contact: "https://t.me",
    image: "/images/alumini/hong_pisey.jpg",
  },
  {
    id: "11",
    name: "Tuon Sora",
    nameKh: "ទួន សុរ៉ា",
    faceBookLink: "https://www.facebook.com/sora.tuon",
    contact: "https://t.me",
    image: "/images/member/sora.jpeg",
  },
  {
    id: "12",
    name: "Phon Sobon",
    nameKh: "ផុន សុបុណ្យ",
    faceBookLink: "https://www.facebook.com/sobon.phon",
    contact: "https://t.me/Phonsobon",
    image: "/images/member/phonsobon.jpg",
  },
  {
    id: "13",
    name: "Cheng Sovanarith",
    nameKh: "ចេង​ សុវណ្ណារិទ្ធិ",
    faceBookLink: "https://www.facebook.com/Sovannarith.Cheng.8989",
    contact: "https://t.me/ChengSovannarith",
    image: "/images/cards/rith.jpg",
  },
  {
    id: "14",
    name: "Sam Sokhuoy",
    nameKh: "សាម សុឃួយ",
    faceBookLink: "https://www.facebook.com/sokhuoy.sam",
    contact: "https://t.me",
    image: "/images/alumini/sam_sokhuoy.jpg",
  }
];